spring.application.name=syncreserve

spring.datasource.url=jdbc:postgresql://localhost:5432/syncreserve_db
spring.datasource.username=postgres
spring.datasource.password=Saranga$2001Madhu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=SyncReserveSecretKeyForJwtAuthentication2026VeryLongSecret
jwt.expiration=86400000

server.port=8080